// src-tauri/src/commands/config_cmd.rs
use crate::services::config_service::ConfigService;
use tauri::{AppHandle, Runtime};
use std::fs;
use std::path::Path;
use walkdir::WalkDir;

#[tauri::command]
pub async fn get_base_directory<R: Runtime>(app: AppHandle<R>) -> Result<Option<String>, String> {
    ConfigService::get_base_path(&app).map_err(|e| e.to_string())
}

#[tauri::command]
pub async fn set_base_directory<R: Runtime>(app: AppHandle<R>, path: String) -> Result<(), String> {
    ConfigService::set_base_path(&app, &path)
}

#[tauri::command]
pub async fn rename_base_directory<R: Runtime>(app: AppHandle<R>, new_name: String) -> Result<(), String> {
    let old_path_opt = ConfigService::get_base_path(&app).map_err(|e| e.to_string())?;
    
    if let Some(old_path_str) = old_path_opt {
        let old_path = Path::new(&old_path_str);
        if let Some(parent) = old_path.parent() {
            let new_path = parent.join(&new_name);
            
            if new_path.exists() {
                return Err("目标文件夹名已存在".to_string());
            }
            
            fs::rename(&old_path, &new_path).map_err(|e| format!("重命名失败: {}", e))?;
            
            let new_path_str = new_path.to_string_lossy().to_string();
            ConfigService::set_base_path(&app, &new_path_str)?;
            
            return Ok(());
        }
    }
    
    Err("无法获取当前数据目录".to_string())
}

#[tauri::command]
pub async fn migrate_base_directory<R: Runtime>(
    app: AppHandle<R>,
    new_path: String,
    move_data: bool,
) -> Result<(), String> {
    let old_path_opt = ConfigService::get_base_path(&app).map_err(|e| e.to_string())?;
    
    // Configure new environment base
    ConfigService::set_base_path(&app, &new_path)?;
    
    if let Some(old_path_str) = old_path_opt {
        if old_path_str == new_path {
            return Ok(());
        }
        
        let old_path = Path::new(&old_path_str);
        let new_path_obj = Path::new(&new_path);
        
        let old_settings = old_path.join("config").join("settings.json");
        let new_settings = new_path_obj.join("config").join("settings.json");
        
        if move_data {
            let old_instances = old_path.join("instances");
            let new_instances = new_path_obj.join("instances");
            
            if old_instances.exists() {
                // Delete empty directory generated by set_base_path for rename target
                let _ = fs::remove_dir_all(&new_instances);
                match fs::rename(&old_instances, &new_instances) {
                    Ok(_) => {},
                    Err(_) => {
                        let _ = fs::create_dir_all(&new_instances);
                        for entry in WalkDir::new(&old_instances).into_iter().filter_map(|e| e.ok()) {
                            let ty = entry.file_type();
                            let relative_path = entry.path().strip_prefix(&old_instances).unwrap();
                            let target_path = new_instances.join(relative_path);

                            if ty.is_dir() {
                                let _ = fs::create_dir_all(&target_path);
                            } else if ty.is_file() {
                                let _ = fs::copy(entry.path(), &target_path);
                            }
                        }
                    }
                }
            }
        }
        
        if old_settings.exists() {
            let _ = fs::copy(&old_settings, &new_settings);
        }
    }
    
    Ok(())
}
