// src-tauri/src/services/instance/vanilla_advancements.rs
//! Minecraft 原版官方成就权威静态字典 (1.12 ~ 1.21+)
//! 包含标准中文标题、描述、图标名称、分类与挑战框架级别。
//! 内存直出，零 I/O、零 ZIP 开销。

#[derive(Debug, Clone, Copy)]
pub struct VanillaAdvancementMeta {
    pub id: &'static str,
    pub title: &'static str,
    pub description: &'static str,
    pub icon: &'static str,
    pub frame_type: &'static str,
    pub category: &'static str,
    pub parent_id: Option<&'static str>,
}

pub fn get_vanilla_advancement(id: &str) -> Option<&'static VanillaAdvancementMeta> {
    VANILLA_ADVANCEMENTS.iter().find(|item| item.id == id)
}

pub static VANILLA_ADVANCEMENTS: &[VanillaAdvancementMeta] = &[
    // =========================================================================
    // 故事 (Story)
    // =========================================================================
    VanillaAdvancementMeta {
        id: "minecraft:story/root",
        title: "Minecraft",
        description: "游戏的核心与故事",
        icon: "grass_block",
        frame_type: "task",
        category: "story",
        parent_id: None,
    },
    VanillaAdvancementMeta {
        id: "minecraft:story/mine_stone",
        title: "采石时代",
        description: "用你的新镐挖掘石头",
        icon: "wooden_pickaxe",
        frame_type: "task",
        category: "story",
        parent_id: Some("minecraft:story/root"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:story/upgrade_tools",
        title: "获得升级",
        description: "制造一把更好的镐",
        icon: "stone_pickaxe",
        frame_type: "task",
        category: "story",
        parent_id: Some("minecraft:story/mine_stone"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:story/smelt_iron",
        title: "热腾腾的成就",
        description: "熔炼出一块铁锭",
        icon: "iron_ingot",
        frame_type: "task",
        category: "story",
        parent_id: Some("minecraft:story/upgrade_tools"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:story/obtain_armor",
        title: "为荣誉而着装",
        description: "用铁制作一件护甲",
        icon: "iron_chestplate",
        frame_type: "task",
        category: "story",
        parent_id: Some("minecraft:story/smelt_iron"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:story/lava_bucket",
        title: "热辣辣的",
        description: "用铁桶装满岩浆",
        icon: "lava_bucket",
        frame_type: "task",
        category: "story",
        parent_id: Some("minecraft:story/smelt_iron"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:story/iron_tools",
        title: "不是挺好“铁”吗",
        description: "升级你的铁镐",
        icon: "iron_pickaxe",
        frame_type: "task",
        category: "story",
        parent_id: Some("minecraft:story/smelt_iron"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:story/deflect_arrow",
        title: "请勿还手",
        description: "用盾牌格挡一次弹射物攻击",
        icon: "shield",
        frame_type: "task",
        category: "story",
        parent_id: Some("minecraft:story/obtain_armor"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:story/form_obsidian",
        title: "冰桶挑战",
        description: "获得一块黑曜石",
        icon: "obsidian",
        frame_type: "task",
        category: "story",
        parent_id: Some("minecraft:story/lava_bucket"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:story/mine_diamond",
        title: "钻石！",
        description: "获得钻石",
        icon: "diamond",
        frame_type: "task",
        category: "story",
        parent_id: Some("minecraft:story/iron_tools"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:story/enter_the_nether",
        title: "深入下界",
        description: "建造、激活并进入一座下界传送门",
        icon: "flint_and_steel",
        frame_type: "task",
        category: "story",
        parent_id: Some("minecraft:story/form_obsidian"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:story/shiny_gear",
        title: "用钻石包裹我",
        description: "钻石护甲能拯救生命",
        icon: "diamond_chestplate",
        frame_type: "task",
        category: "story",
        parent_id: Some("minecraft:story/mine_diamond"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:story/enchant_item",
        title: "附魔大师",
        description: "在附魔台上给一件物品附魔",
        icon: "enchanted_book",
        frame_type: "task",
        category: "story",
        parent_id: Some("minecraft:story/mine_diamond"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:story/cure_zombie_villager",
        title: "僵尸医生",
        description: "削弱并治愈一个僵尸村民",
        icon: "golden_apple",
        frame_type: "goal",
        category: "story",
        parent_id: Some("minecraft:story/enter_the_nether"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:story/follow_ender_eye",
        title: "眼见为实",
        description: "跟随末影之眼",
        icon: "ender_eye",
        frame_type: "task",
        category: "story",
        parent_id: Some("minecraft:story/enter_the_nether"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:story/enter_the_end",
        title: "结束了？",
        description: "进入末地传送门",
        icon: "end_stone",
        frame_type: "task",
        category: "story",
        parent_id: Some("minecraft:story/follow_ender_eye"),
    },

    // =========================================================================
    // 下界 (Nether)
    // =========================================================================
    VanillaAdvancementMeta {
        id: "minecraft:nether/root",
        title: "下界",
        description: "带上夏天的衣服",
        icon: "red_nether_bricks",
        frame_type: "task",
        category: "nether",
        parent_id: None,
    },
    VanillaAdvancementMeta {
        id: "minecraft:nether/return_to_sender",
        title: "见鬼去吧",
        description: "用一发火球消灭恶魂",
        icon: "fire_charge",
        frame_type: "challenge",
        category: "nether",
        parent_id: Some("minecraft:nether/root"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:nether/find_bastion",
        title: "那些光辉岁月",
        description: "进入堡垒遗迹",
        icon: "polished_blackstone_bricks",
        frame_type: "task",
        category: "nether",
        parent_id: Some("minecraft:nether/root"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:nether/obtain_ancient_debris",
        title: "隐藏在深处",
        description: "获得远古残骸",
        icon: "ancient_debris",
        frame_type: "task",
        category: "nether",
        parent_id: Some("minecraft:nether/root"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:nether/fast_travel",
        title: "超空间折跃",
        description: "利用下界穿行主世界 7 公里",
        icon: "map",
        frame_type: "challenge",
        category: "nether",
        parent_id: Some("minecraft:nether/return_to_sender"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:nether/find_fortress",
        title: "可怕的要塞",
        description: "勇闯下界要塞",
        icon: "nether_bricks",
        frame_type: "task",
        category: "nether",
        parent_id: Some("minecraft:nether/root"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:nether/obtain_crying_obsidian",
        title: "是谁在切洋葱？",
        description: "获得哭泣的黑曜石",
        icon: "crying_obsidian",
        frame_type: "task",
        category: "nether",
        parent_id: Some("minecraft:nether/root"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:nether/distract_piglin",
        title: "闪闪发光",
        description: "用黄金引开猪灵",
        icon: "gold_ingot",
        frame_type: "task",
        category: "nether",
        parent_id: Some("minecraft:nether/root"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:nether/ride_strider",
        title: "这只猪有轮子吗？",
        description: "骑上用诡异菌钓竿操控的炽足兽",
        icon: "warped_fungus_on_a_stick",
        frame_type: "task",
        category: "nether",
        parent_id: Some("minecraft:nether/root"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:nether/uneasy_alliance",
        title: "不稳定的同盟",
        description: "将一只恶魂从下界救入主世界...然后消灭它",
        icon: "ghast_tear",
        frame_type: "challenge",
        category: "nether",
        parent_id: Some("minecraft:nether/return_to_sender"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:nether/loot_bastion",
        title: "战猪",
        description: "掠夺堡垒遗迹中的箱子",
        icon: "chest",
        frame_type: "task",
        category: "nether",
        parent_id: Some("minecraft:nether/find_bastion"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:nether/use_lodestone",
        title: "指引方向",
        description: "对磁石使用指南针",
        icon: "lodestone",
        frame_type: "task",
        category: "nether",
        parent_id: Some("minecraft:nether/find_bastion"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:nether/netherite_armor",
        title: "以残骸重铸",
        description: "获得全套下界合金护甲",
        icon: "netherite_chestplate",
        frame_type: "challenge",
        category: "nether",
        parent_id: Some("minecraft:nether/obtain_ancient_debris"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:nether/get_wither_skull",
        title: "诡异可怖的骷髅",
        description: "获取凋灵骷髅头颅",
        icon: "wither_skeleton_skull",
        frame_type: "task",
        category: "nether",
        parent_id: Some("minecraft:nether/find_fortress"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:nether/obtain_blaze_rod",
        title: "进入烈焰之中",
        description: "从烈焰人身上获取烈焰棒",
        icon: "blaze_rod",
        frame_type: "task",
        category: "nether",
        parent_id: Some("minecraft:nether/find_fortress"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:nether/charge_respawn_anchor",
        title: "“七”不符合",
        description: "将重生锚充能至最大值",
        icon: "respawn_anchor",
        frame_type: "task",
        category: "nether",
        parent_id: Some("minecraft:nether/obtain_crying_obsidian"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:nether/ride_strider_in_overworld_lava",
        title: "舒适惬意",
        description: "在主世界的岩浆湖上骑乘炽足兽漫游",
        icon: "warped_fungus_on_a_stick",
        frame_type: "task",
        category: "nether",
        parent_id: Some("minecraft:nether/ride_strider"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:nether/explore_nether",
        title: "炙热目的地",
        description: "探索下界所有的生物群系",
        icon: "netherite_boots",
        frame_type: "challenge",
        category: "nether",
        parent_id: Some("minecraft:nether/ride_strider"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:nether/summon_wither",
        title: "见证凋灵",
        description: "召唤凋灵",
        icon: "nether_star",
        frame_type: "task",
        category: "nether",
        parent_id: Some("minecraft:nether/get_wither_skull"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:nether/brew_potion",
        title: "本地酿造厂",
        description: "酿造一瓶药水",
        icon: "potion",
        frame_type: "task",
        category: "nether",
        parent_id: Some("minecraft:nether/obtain_blaze_rod"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:nether/create_beacon",
        title: "信标工程师",
        description: "制造并放置一个信标",
        icon: "beacon",
        frame_type: "task",
        category: "nether",
        parent_id: Some("minecraft:nether/summon_wither"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:nether/all_potions",
        title: "猛烈狂暴的鸡尾酒",
        description: "同时拥有所有药水效果",
        icon: "milk_bucket",
        frame_type: "challenge",
        category: "nether",
        parent_id: Some("minecraft:nether/brew_potion"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:nether/create_full_beacon",
        title: "信标大师",
        description: "将一个信标带到最高能量",
        icon: "beacon",
        frame_type: "goal",
        category: "nether",
        parent_id: Some("minecraft:nether/create_beacon"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:nether/all_effects",
        title: "狂乱狂暴狂欢",
        description: "同时拥有所有状态效果",
        icon: "bucket",
        frame_type: "challenge",
        category: "nether",
        parent_id: Some("minecraft:nether/all_potions"),
    },

    // =========================================================================
    // 末地 (The End)
    // =========================================================================
    VanillaAdvancementMeta {
        id: "minecraft:end/root",
        title: "末地",
        description: "还是新的开始？",
        icon: "end_stone",
        frame_type: "task",
        category: "the_end",
        parent_id: None,
    },
    VanillaAdvancementMeta {
        id: "minecraft:end/kill_dragon",
        title: "解放末地",
        description: "祝你好运",
        icon: "dragon_head",
        frame_type: "task",
        category: "the_end",
        parent_id: Some("minecraft:end/root"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:end/dragon_egg",
        title: "次世代",
        description: "抱走龙蛋",
        icon: "dragon_egg",
        frame_type: "goal",
        category: "the_end",
        parent_id: Some("minecraft:end/kill_dragon"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:end/enter_end_gateway",
        title: "远程逃生",
        description: "逃离主岛屿",
        icon: "ender_pearl",
        frame_type: "task",
        category: "the_end",
        parent_id: Some("minecraft:end/kill_dragon"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:end/respawn_dragon",
        title: "重新来过",
        description: "重新召唤末影龙",
        icon: "end_crystal",
        frame_type: "goal",
        category: "the_end",
        parent_id: Some("minecraft:end/kill_dragon"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:end/dragon_breath",
        title: "来点薄荷糖？",
        description: "在玻璃瓶中收集龙息",
        icon: "dragon_breath",
        frame_type: "goal",
        category: "the_end",
        parent_id: Some("minecraft:end/kill_dragon"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:end/find_end_city",
        title: "城市远景",
        description: "去走走，末地城可漂亮了",
        icon: "purpur_block",
        frame_type: "task",
        category: "the_end",
        parent_id: Some("minecraft:end/enter_end_gateway"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:end/elytra",
        title: "天空即为极限",
        description: "找到鞘翅",
        icon: "elytra",
        frame_type: "goal",
        category: "the_end",
        parent_id: Some("minecraft:end/find_end_city"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:end/levitate",
        title: "好高啊",
        description: "被潜影贝的攻击悬浮上升 50 个方块",
        icon: "shulker_shell",
        frame_type: "challenge",
        category: "the_end",
        parent_id: Some("minecraft:end/find_end_city"),
    },

    // =========================================================================
    // 冒险 (Adventure)
    // =========================================================================
    VanillaAdvancementMeta {
        id: "minecraft:adventure/root",
        title: "冒险",
        description: "探险、战斗与生存",
        icon: "map",
        frame_type: "task",
        category: "adventure",
        parent_id: None,
    },
    VanillaAdvancementMeta {
        id: "minecraft:adventure/voluntary_exile",
        title: "自投罗网",
        description: "消灭一名袭击队长",
        icon: "ominous_banner",
        frame_type: "task",
        category: "adventure",
        parent_id: Some("minecraft:adventure/root"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:adventure/spyglass_at_parrot",
        title: "那是鸟吗？",
        description: "透过望远镜看鹦鹉",
        icon: "spyglass",
        frame_type: "task",
        category: "adventure",
        parent_id: Some("minecraft:adventure/root"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:adventure/kill_a_mob",
        title: "怪物猎人",
        description: "消灭任一敌对怪物",
        icon: "iron_sword",
        frame_type: "task",
        category: "adventure",
        parent_id: Some("minecraft:adventure/root"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:adventure/trade",
        title: "交易伙伴",
        description: "与村民进行一次成功的交易",
        icon: "emerald",
        frame_type: "task",
        category: "adventure",
        parent_id: Some("minecraft:adventure/root"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:adventure/honey_block_slide",
        title: "甜蜜的滑行",
        description: "从蜂蜜块表面滑下以缓冲下落",
        icon: "honey_block",
        frame_type: "task",
        category: "adventure",
        parent_id: Some("minecraft:adventure/root"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:adventure/ol_betsy",
        title: "老伙计",
        description: "使用弩射出一箭",
        icon: "crossbow",
        frame_type: "task",
        category: "adventure",
        parent_id: Some("minecraft:adventure/root"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:adventure/sleep_in_bed",
        title: "甜蜜美梦",
        description: "睡在床上以改变重生点",
        icon: "red_bed",
        frame_type: "task",
        category: "adventure",
        parent_id: Some("minecraft:adventure/root"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:adventure/hero_of_the_village",
        title: "村庄英雄",
        description: "成功保卫一座村庄抵御袭击",
        icon: "ominous_banner",
        frame_type: "challenge",
        category: "adventure",
        parent_id: Some("minecraft:adventure/voluntary_exile"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:adventure/throw_trident",
        title: "扔得一手好叉",
        description: "向某物投掷三叉戟",
        icon: "trident",
        frame_type: "task",
        category: "adventure",
        parent_id: Some("minecraft:adventure/ol_betsy"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:adventure/shoot_crossbow",
        title: "弩手初成",
        description: "用弩射击一个目标",
        icon: "crossbow",
        frame_type: "task",
        category: "adventure",
        parent_id: Some("minecraft:adventure/ol_betsy"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:adventure/adventuring_time",
        title: "探索的时光",
        description: "发现所有的生物群系",
        icon: "diamond_boots",
        frame_type: "challenge",
        category: "adventure",
        parent_id: Some("minecraft:adventure/sleep_in_bed"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:adventure/kill_all_mobs",
        title: "怪物猎人总动员",
        description: "消灭每一种敌对怪物",
        icon: "diamond_sword",
        frame_type: "challenge",
        category: "adventure",
        parent_id: Some("minecraft:adventure/kill_a_mob"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:adventure/bullseye",
        title: "靶心",
        description: "从至少 30 米外正中靶心",
        icon: "target",
        frame_type: "challenge",
        category: "adventure",
        parent_id: Some("minecraft:adventure/shoot_crossbow"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:adventure/sniper_duel",
        title: "狙击手的对决",
        description: "从 50 米外用弓消灭一只骷髅",
        icon: "bow",
        frame_type: "challenge",
        category: "adventure",
        parent_id: Some("minecraft:adventure/kill_a_mob"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:adventure/under_lock_and_key",
        title: "上锁加固",
        description: "用试炼钥匙开启试炼宝箱",
        icon: "trial_key",
        frame_type: "task",
        category: "adventure",
        parent_id: Some("minecraft:adventure/root"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:adventure/revaulting",
        title: "再次开启",
        description: "用沉重试炼钥匙开启沉重试炼宝箱",
        icon: "trial_key",
        frame_type: "challenge",
        category: "adventure",
        parent_id: Some("minecraft:adventure/under_lock_and_key"),
    },

    // =========================================================================
    // 农业 (Husbandry)
    // =========================================================================
    VanillaAdvancementMeta {
        id: "minecraft:husbandry/root",
        title: "农业",
        description: "世界充满朋友与食物",
        icon: "hay_block",
        frame_type: "task",
        category: "husbandry",
        parent_id: None,
    },
    VanillaAdvancementMeta {
        id: "minecraft:husbandry/breed_an_animal",
        title: "自然选择",
        description: "繁殖两只动物",
        icon: "wheat",
        frame_type: "task",
        category: "husbandry",
        parent_id: Some("minecraft:husbandry/root"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:husbandry/tame_an_animal",
        title: "最好的朋友",
        description: "驯服一只动物",
        icon: "lead",
        frame_type: "task",
        category: "husbandry",
        parent_id: Some("minecraft:husbandry/root"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:husbandry/plant_seed",
        title: "种子成荫",
        description: "播种种子并看着它长大",
        icon: "wheat_seeds",
        frame_type: "task",
        category: "husbandry",
        parent_id: Some("minecraft:husbandry/root"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:husbandry/fishy_business",
        title: "捕鱼达人",
        description: "钓上一条鱼",
        icon: "fishing_rod",
        frame_type: "task",
        category: "husbandry",
        parent_id: Some("minecraft:husbandry/root"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:husbandry/safely_harvest_honey",
        title: "蜜蜂好友",
        description: "在营火上用玻璃瓶收集蜂蜜而不惹怒蜜蜂",
        icon: "honey_bottle",
        frame_type: "task",
        category: "husbandry",
        parent_id: Some("minecraft:husbandry/root"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:husbandry/a_balanced_diet",
        title: "均衡饮食",
        description: "吃下所有能吃的东西，即使对身体不好",
        icon: "apple",
        frame_type: "challenge",
        category: "husbandry",
        parent_id: Some("minecraft:husbandry/plant_seed"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:husbandry/bred_all_animals",
        title: "双双成对",
        description: "繁殖每一种动物！",
        icon: "golden_carrot",
        frame_type: "challenge",
        category: "husbandry",
        parent_id: Some("minecraft:husbandry/breed_an_animal"),
    },
    VanillaAdvancementMeta {
        id: "minecraft:husbandry/complete_catalogue",
        title: "全套猫咪图鉴",
        description: "驯服所有猫的品种！",
        icon: "cod",
        frame_type: "challenge",
        category: "husbandry",
        parent_id: Some("minecraft:husbandry/tame_an_animal"),
    },
];
